modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="cassie"
version="0.0.1"
displayName="C.A.S.S.I.E (SCP:SL TTS)"
credits="SCP:SL"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="5UP3R TH30 B4G"

[[dependencies.cassie]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




